name: bottom_navy_bar
description: A beautiful and animated bottom navigation. The navigation bar uses your current theme, but you are free to customize it.
version: 7.0.0
homepage: https://github.com/pedromassango/bottom_navy_bar

environment:
  sdk: ">=2.17.0-0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
